//! XYZ → RGB matrices for the three [`crate::DcpTargetGamut`]
//! variants used by the Tier 12 (DCP / Xyz12) pipeline.
//!
//! Each matrix is `[[f32; 3]; 3]` — applied as
//! `[R G B]^T = M · [X Y Z]^T` per pixel after the SMPTE ST 428-1
//! inverse-OETF stage produces linear XYZ.
//!
//! # Derivation provenance
//!
//! Generated by running the committed example tool:
//!
//! ```ignore
//! cargo run --release --example derive_xyz_matrices
//! ```
//!
//! The tool runs the standard primary-scaling algorithm (ITU-R BT.709-6
//! §3 / SMPTE ST 432-1 / ITU-R BT.2020-2 conventions):
//!
//! 1. `XYZ_primary = (x/y, 1, (1 - x - y) / y)` per chromaticity.
//! 2. Solve `M_unscaled · S = W_xyz` for primary scales S.
//! 3. `M_rgb_to_xyz` columns = unscaled primary XYZ × S.
//! 4. `M_xyz_to_rgb = inverse(M_rgb_to_xyz)`.
//!
//! All math runs at f64 internally; values below are narrowed to f32
//! at the end so per-pixel SIMD work stays single-precision.
//!
//! # Cross-validation against published values
//!
//! The Rec.709 inverse matrix per ITU-R BT.709-6 §3.4 (also IEC
//! 61966-2-1) is published as approximately:
//!
//! ```text
//! [  3.240479,  -1.537150,  -0.498535 ]
//! [ -0.969256,   1.875992,   0.041556 ]
//! [  0.055648,  -0.204043,   1.057311 ]
//! ```
//!
//! The values below match to 4–5 decimals; the small published
//! divergence is due to BT.709's published matrix being computed with
//! extended-precision D65 white point (~6 decimals) versus the spec's
//! 4-decimal chromaticity row (`0.3127, 0.3290`). My derivation is
//! canonical for the chromaticities printed in the standard.
//!
//! Same observation for DCI-P3 (SMPTE RP 431-2 / ST 432-1 D65 variant)
//! and Rec.2020 (ITU-R BT.2020-2): derived matrix values agree to 4–5
//! decimals with each standard's published inverse.

use crate::DcpTargetGamut;

/// XYZ → RGB matrix for **Rec.709 / sRGB** (D65 output white).
///
/// Derived from chromaticity coordinates in ITU-R BT.709-6 §3, IEC
/// 61966-2-1: R=(0.640, 0.330), G=(0.300, 0.600), B=(0.150, 0.060),
/// W=D65=(0.3127, 0.3290).
///
/// f64 source values:
///
/// ```text
/// [  3.2409699419,  -1.5373831776,  -0.4986107603]
/// [ -0.9692436363,   1.8759675015,   0.0415550574]
/// [  0.0556300797,  -0.2039769589,   1.0569715142]
/// ```
pub(crate) const M_XYZ_TO_RGB_REC709: [[f32; 3]; 3] = [
  [3.240_97_f32, -1.537_383_f32, -0.498_610_8_f32],
  [-0.969_243_7_f32, 1.875_967_5_f32, 0.041_555_06_f32],
  [0.055_630_08_f32, -0.203_976_96_f32, 1.056_971_5_f32],
];

/// XYZ → RGB matrix for **DCI-P3 D65** (D65 output white) — DCP
/// mastering default per SMPTE ST 428-1 / RP 431-2.
///
/// Derived from chromaticity coordinates in SMPTE RP 431-2 / SMPTE ST
/// 432-1 (D65 variant): R=(0.680, 0.320), G=(0.265, 0.690),
/// B=(0.150, 0.060), W=D65=(0.3127, 0.3290).
///
/// f64 source values:
///
/// ```text
/// [  2.4934969119,  -0.9313836179,  -0.4027107845]
/// [ -0.8294889696,   1.7626640603,   0.0236246858]
/// [  0.0358458302,  -0.0761723893,   0.9568845240]
/// ```
pub(crate) const M_XYZ_TO_RGB_DCI_P3: [[f32; 3]; 3] = [
  [2.493_497_f32, -0.931_383_6_f32, -0.402_710_78_f32],
  [-0.829_489_f32, 1.762_664_f32, 0.023_624_687_f32],
  [0.035_845_83_f32, -0.076_172_39_f32, 0.956_884_5_f32],
];

/// XYZ → RGB matrix for **Rec.2020** (D65 output white).
///
/// Derived from chromaticity coordinates in ITU-R BT.2020-2:
/// R=(0.708, 0.292), G=(0.170, 0.797), B=(0.131, 0.046),
/// W=D65=(0.3127, 0.3290).
///
/// f64 source values:
///
/// ```text
/// [  1.7166511880,  -0.3556707838,  -0.2533662814]
/// [ -0.6666843518,   1.6164812366,   0.0157685458]
/// [  0.0176398574,  -0.0427706133,   0.9421031212]
/// ```
pub(crate) const M_XYZ_TO_RGB_REC2020: [[f32; 3]; 3] = [
  [1.716_651_f32, -0.355_670_78_f32, -0.253_366_3_f32],
  [-0.666_684_3_f32, 1.616_481_2_f32, 0.015_768_547_f32],
  [0.017_639_857_f32, -0.042_770_613_f32, 0.942_103_15_f32],
];

/// Returns the active XYZ → RGB matrix for the given target gamut.
///
/// `inline(always)` so the lookup compiles into a register-resident
/// 3×3 constant at the call site for monomorphised dispatch
/// (`DcpTargetGamut` is small + Copy).
#[cfg_attr(not(tarpaulin), inline(always))]
pub(crate) const fn xyz_to_rgb_matrix(g: DcpTargetGamut) -> [[f32; 3]; 3] {
  match g {
    DcpTargetGamut::DciP3 => M_XYZ_TO_RGB_DCI_P3,
    DcpTargetGamut::Rec709 => M_XYZ_TO_RGB_REC709,
    DcpTargetGamut::Rec2020 => M_XYZ_TO_RGB_REC2020,
  }
}

/// SMPTE ST 428-1 §8 normalising factor: linear XYZ at the maximum
/// 12-bit code (4095/4095) is `1.0 / 0.91653`. Multiplying after
/// `(x/4095)^2.6` folds the spec's normalisation into the math.
pub(crate) const SMPTE428_INV_NORM: f32 = 1.0_f32 / 0.91653_f32;

/// `1.0 / 4095.0` — pre-divide so the inner loop is a multiply.
pub(crate) const INV_4095: f32 = 1.0_f32 / 4095.0_f32;

/// Mask for the active 12 bits of an XYZ12 sample. Upper 4 bits are
/// reserved zero per SMPTE ST 428-1; kernels mask defensively.
pub(crate) const SAMPLE_MASK: u16 = 0x0FFF;
