#!/usr/bin/env python3
"""Regenerates src/resample/pil_goldens.rs.

Golden outputs for the Pillow (PIL) `Image.resize` parity harness — the
oracle the scalar separable filter resampler is validated against within
+-1 LSB (u8 / u16) or a small float tolerance (f32). Sources are NOT
stored: both this script and the Rust tests synthesize them with the same
LCG (state = state * 1664525 + 1013904223 mod 2^32; byte = (state >> 8) &
0xFF), so the fixture carries only PIL's outputs.

Kernel <-> PIL resample filter mapping (the crate's `FilterKernel`s):
    Triangle   <-> BILINEAR
    CatmullRom <-> BICUBIC
    Lanczos3   <-> LANCZOS

Only DOWNSCALE cases (integer + fractional ratios). Modes:
    L     -> u8  gray (1 channel)
    RGB   -> u8  (3 channels)
    I;16  -> u16 gray (1 channel)
    F     -> f32 gray (1 channel, unclamped)

u8/u16 goldens are plain integers; f32 goldens are emitted as
`f32::from_bits(..)` so the checked-in value is bit-exact (no decimal
round-trip loss).

Usage: /tmp/p3-venv/bin/python ci/gen_pil_goldens.py  (needs Pillow + numpy)
"""

import struct

import numpy as np
from PIL import Image

# Kernel name <-> (PIL filter attribute, Rust kernel type).
KERNELS = [
    ("BILINEAR", "Triangle"),
    ("BICUBIC", "CatmullRom"),
    ("LANCZOS", "Lanczos3"),
]

# (label, src_w, src_h, out_w, out_h, lcg seed). Integer + fractional
# ratios, a couple of aspect-changing 1080p-ish downscales, and tiny grids
# that stress the clamped edge windows.
GEOMS = [
    ("8x8_to_4x4", 8, 8, 4, 4, 0x1111),
    ("8x8_to_3x3", 8, 8, 3, 3, 0x1212),
    ("64x48_to_17x11", 64, 48, 17, 11, 0x2222),
    ("96x96_to_24x24", 96, 96, 24, 24, 0x2323),
    ("200x117_to_67x41", 200, 117, 67, 41, 0x4444),
    ("1920x1080_to_640x360", 1920, 1080, 640, 360, 0x5555),
    ("1000x1000_to_333x333", 1000, 1000, 333, 333, 0x6666),
]

# (mode label, PIL mode, channels, element rust type, numpy dtype).
#
# u16 uses PIL's `I` (int32) mode, NOT `I;16`: the `I` / `F` 32bpc
# resampler is the faithful double-precision path (it keeps a wide
# intermediate between the two passes and only rounds at the end), whereas
# Pillow's legacy `I;16` resize diverges tens of LSB from a faithful
# windowed filter. The source values are still the same u16 numbers the
# Rust fixture synthesizes (carried in an int32 image); the output is
# clamped to the u16 range to match the crate's u16-output clamp.
MODES = [
    ("GRAY", "L", 1, "u8", np.uint8),
    ("RGB", "RGB", 3, "u8", np.uint8),
    ("I16", "I", 1, "u16", np.int32),
    ("F32", "F", 1, "f32", np.float32),
]


def lcg_bytes(n: int, seed: int) -> np.ndarray:
    state = seed & 0xFFFFFFFF
    out = np.empty(n, dtype=np.uint8)
    for i in range(n):
        state = (state * 1664525 + 1013904223) & 0xFFFFFFFF
        out[i] = (state >> 8) & 0xFF
    return out


def f32_bits(x: float) -> int:
    return struct.unpack("<I", struct.pack("<f", np.float32(x)))[0]


def make_source(mode_np, channels, sw, sh, seed):
    raw = lcg_bytes(sw * sh * channels, seed)
    if mode_np == np.int32:
        # u16 values (`(v << 8) | roll(v, 1)`, spreading signal into the low
        # byte) carried in an int32 image for PIL's faithful `I` resampler.
        # Matches the Rust fixture's `source_u16`.
        vals = raw.astype(np.uint16)
        vals = (vals << 8) | np.roll(vals, 1)
        arr = vals.astype(np.int32).reshape((sh, sw))
    elif mode_np == np.float32:
        # Non-negative float samples with a fractional part — the F-mode
        # analogue of the area f32 fixture.
        arr = (raw.astype(np.float32) + (raw.astype(np.float32) / 256.0)).reshape(
            (sh, sw)
        )
    else:
        shape = (sh, sw) if channels == 1 else (sh, sw, channels)
        arr = raw.reshape(shape)
    return arr


def main() -> None:
    lines = [
        "//! Pillow (PIL) `Image.resize` golden outputs — GENERATED by",
        "//! `ci/gen_pil_goldens.py`; do not edit by hand. Sources are",
        "//! synthesized in the tests with the same LCG, so only PIL's",
        "//! outputs live here. Kernel map: Triangle<->BILINEAR,",
        "//! CatmullRom<->BICUBIC, Lanczos3<->LANCZOS. Downscale only.",
        "",
        "#![allow(clippy::unreadable_literal, clippy::excessive_precision)]",
        "",
        "/// `(src_w, src_h, out_w, out_h, channels, lcg_seed, pil_output)`.",
        "pub(super) type GoldenU8 = (usize, usize, usize, usize, usize, u32, &'static [u8]);",
        "/// u16 element golden (PIL faithful `I` resampler, clamped u16).",
        "pub(super) type GoldenU16 = (usize, usize, usize, usize, usize, u32, &'static [u16]);",
        "/// f32 element golden (unclamped `F` mode); values are bit-exact.",
        "pub(super) type GoldenF32 = (usize, usize, usize, usize, usize, u32, &'static [f32]);",
        "",
    ]

    # Group by Rust element type -> list of (kernel_rust, const_name).
    u8_cases = []
    u16_cases = []
    f32_cases = []

    for kpil, krust in KERNELS:
        pil_filter = getattr(Image.Resampling, kpil)
        for glabel, sw, sh, ow, oh, seed in GEOMS:
            for mlabel, pil_mode, channels, rtype, mode_np in MODES:
                arr = make_source(mode_np, channels, sw, sh, seed)
                img = Image.fromarray(arr, mode=pil_mode)
                out = img.resize((ow, oh), resample=pil_filter)
                out_arr = np.asarray(out)
                flat = out_arr.reshape(-1)
                name = f"CASE_{krust.upper()}_{glabel.upper()}_{mlabel}"
                lines.append("#[rustfmt::skip]")
                if rtype == "u8":
                    body = ", ".join(str(int(v)) for v in flat)
                    lines.append(
                        f"pub(super) const {name}: GoldenU8 = "
                        f"({sw}, {sh}, {ow}, {oh}, {channels}, 0x{seed:X}, &[{body}]);"
                    )
                    u8_cases.append((krust, name))
                elif rtype == "u16":
                    # PIL `I` output is int32; clamp to the u16 range to
                    # match the crate's u16-output clamp (the faithful
                    # 32bpc resampler can overshoot via negative lobes).
                    body = ", ".join(str(int(min(65535, max(0, int(v))))) for v in flat)
                    lines.append(
                        f"pub(super) const {name}: GoldenU16 = "
                        f"({sw}, {sh}, {ow}, {oh}, {channels}, 0x{seed:X}, &[{body}]);"
                    )
                    u16_cases.append((krust, name))
                else:
                    body = ", ".join(f"f32::from_bits(0x{f32_bits(v):08X})" for v in flat)
                    lines.append(
                        f"pub(super) const {name}: GoldenF32 = "
                        f"({sw}, {sh}, {ow}, {oh}, {channels}, 0x{seed:X}, &[{body}]);"
                    )
                    f32_cases.append((krust, name))
                lines.append("")

    def emit_table(rust_kernel, cases, ty, table):
        names = [n for (k, n) in cases if k == rust_kernel]
        lines.append(
            f"/// {rust_kernel} {ty} goldens, for the parity test to sweep."
        )
        lines.append(
            f"pub(super) const {table}: &[Golden{ty.upper()}] = &[{', '.join(names)}];"
        )
        lines.append("")

    for _kpil, krust in KERNELS:
        emit_table(krust, u8_cases, "u8", f"{krust.upper()}_U8")
        emit_table(krust, u16_cases, "u16", f"{krust.upper()}_U16")
        emit_table(krust, f32_cases, "f32", f"{krust.upper()}_F32")

    with open("src/resample/pil_goldens.rs", "w") as f:
        f.write("\n".join(lines))
    total = len(u8_cases) + len(u16_cases) + len(f32_cases)
    print(f"wrote {total} cases ({len(u8_cases)} u8, {len(u16_cases)} u16, {len(f32_cases)} f32)")


if __name__ == "__main__":
    main()
