#!/usr/bin/env python3
"""Regenerates src/resample/cv2_goldens.rs.

Golden outputs for the cv2.INTER_AREA parity harness. Sources are NOT
stored: both this script and the Rust tests synthesize them with the
same LCG (state = state * 1664525 + 1013904223 mod 2^32; byte =
(state >> 8) & 0xFF), so the fixture carries only cv2's outputs.

Usage: python3 ci/gen_cv2_goldens.py  (needs opencv-python + numpy)
"""

import numpy as np
import cv2

# (name, src_w, src_h, out_w, out_h, channels, lcg seed)
CASES = [
    ("CASE_8X8_TO_3X3_GRAY", 8, 8, 3, 3, 1, 0x1111),
    ("CASE_64X48_TO_17X11_GRAY", 64, 48, 17, 11, 1, 0x2222),
    ("CASE_31X29_TO_13X7_GRAY", 31, 29, 13, 7, 1, 0x3333),
    ("CASE_200X117_TO_67X41_GRAY", 200, 117, 67, 41, 1, 0x4444),
    ("CASE_40X28_TO_7X5_RGB", 40, 28, 7, 5, 3, 0x5555),
]


def lcg_bytes(n: int, seed: int) -> np.ndarray:
    state = seed & 0xFFFFFFFF
    out = np.empty(n, dtype=np.uint8)
    for i in range(n):
        state = (state * 1664525 + 1013904223) & 0xFFFFFFFF
        out[i] = (state >> 8) & 0xFF
    return out


def main() -> None:
    lines = [
        "//! cv2.INTER_AREA golden outputs — GENERATED by",
        "//! `ci/gen_cv2_goldens.py`; do not edit by hand. Sources are",
        "//! synthesized in the tests with the same LCG, so only cv2's",
        "//! outputs live here.",
        "",
        "/// `(src_w, src_h, out_w, out_h, channels, lcg_seed, cv2_output)`",
        "pub(super) type GoldenCase = (usize, usize, usize, usize, usize, u32, &'static [u8]);",
        "",
    ]
    names = []
    for name, sw, sh, ow, oh, c, seed in CASES:
        src = lcg_bytes(sw * sh * c, seed).reshape(
            (sh, sw) if c == 1 else (sh, sw, c)
        )
        out = cv2.resize(src, (ow, oh), interpolation=cv2.INTER_AREA)
        flat = out.reshape(-1)
        body = ", ".join(str(b) for b in flat)
        lines.append(f"#[rustfmt::skip]")
        lines.append(
            f"pub(super) const {name}: GoldenCase = "
            f"({sw}, {sh}, {ow}, {oh}, {c}, 0x{seed:X}, &[{body}]);"
        )
        lines.append("")
        names.append(name)
    lines.append("/// Every golden case, for the parity test to sweep.")
    lines.append(
        f"pub(super) const ALL: &[GoldenCase] = &[{', '.join(names)}];"
    )
    lines.append("")
    with open("src/resample/cv2_goldens.rs", "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {len(names)} cases")


if __name__ == "__main__":
    main()
